MVCSTOK/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
//entity yani veritabanının dosya yolunu verdik.
using MVCSTOK.Models.Entity;

namespace MVCSTOK.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        //veritabanından db adında bir nesne oluşturduk.
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            //urunler tablosunu liste şeklinde değerler degişkene atarak return view de terar çalışmasını sağladık.
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }

        [HttpGet]   
        public ActionResult Yeniurun()
        {
            //dropdownlist e kategorileri yazdırmak için linq sorgusu kullandık.
            List<SelectListItem> degerler = ( from i in db.TBLKATEGORILER.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = i.KATEGORIAD,
                                                  Value = i.KATEGORIID.ToString()
                                              }).ToList();
            ViewBag.dgr = degerler;
            return View();  
        }
        [HttpPost]  
        public ActionResult Yeniurun( TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m=>m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SIL(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLURUNLER.Find(id);

            //dropdownlist e kategorileri yazdırmak için linq sorgusu kullandık.
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;

            return View("UrunGetir", urun);
        }

        public ActionResult Guncelle(TBLURUNLER p)
        {
            var urun = db.TBLURUNLER.Find(p.URUNID);
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;   
            urun.STOK = p.STOK; 
            urun.FIYAT = p.FIYAT;
            // urun.URUNKATEGORI = p.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MVCSTOK/Views/Urun/Index.cshtml
@using MVCSTOK.Models.Entity
@model List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>URUN ID</th>
            <th>URUN AD</th>
            <th>MARKA</th>
            <th>URUN KATEGORİ</th>
            <th>FİYAT</th>
            <th>STOK</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urun in Model)
        {
            <tr>
                <td>@urun.URUNID</td>
                <td>@urun.URUNAD</td>
                <td>@urun.MARKA</td>
                <td>@urun.TBLKATEGORILER.KATEGORIAD</td>
                <td>@urun.FIYAT</td>
                <td>@urun.STOK</td>
                <td><a href="/URUN/SIL/@urun.URUNID" class="btn btn-danger">SİL</a></td>
                <td><a href="/URUN/UrunGetir/@urun.URUNID" class="btn btn-success">GÜNCELLE</a></td>
            </tr>
        }

    </tbody>

</table>

<a class="btn btn-primary" href="/URUN/Yeniurun/">YENİ URUN EKLE</a>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

<script>
    $('#tbl1').DataTable();
</script>

MVCSTOK/Views/Urun/UrunGetir.cshtml
@model MVCSTOK.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{

    <div class="form-group">

        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m=>m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr , new {@class="form-control"} )

        @*@Html.TextBoxFor(m => m.URUNKATEGORI, new { @class = "form-control" })*@
        <br />
        @Html.LabelFor(m => m.FIYAT)
        @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">Ürün Güncelle</button>



    </div>

}

MVCSTOK/Views/Urun/Yeniurun.cshtml
@model MVCSTOK.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "Yeniurun";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Ürün Adı</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        <input type="text" class="form-control" name="URUNAD" required="" maxlength="50" />
    </div>
    <div>
        <label>Marka Adı</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        <input type="text" class="form-control" name="MARKA" required="" maxlength="50"  />
    </div>
    <div>
        <label>Kategori</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID,(List<SelectListItem>) ViewBag.dgr, new {@class="form-control" })
    </div>
    <div>
        <label>Fiyat</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        <input type="text" class="form-control" name="FIYAT" required=""/>
    </div>
    <div>
        <label>Stok</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        <input type="text" class="form-control" name="STOK" required="" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Ürün Ekle</button>
    </div>

</form>