MVCSTOK/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCSTOK.Models.Entity;

namespace MVCSTOK.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri

        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLMUSTERILER select d;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());  
            //var degerler = db.TBLMUSTERILER.ToList();
            //return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var Musteri = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", Musteri);
        }

        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD=p1.MUSTERIAD; 
            musteri.MUSTERISOYAD=p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("index");
        }

    }
}

MVCSTOK/Views/Musteri/Index.cshtml
@using MVCSTOK.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index","Musteri",FormMethod.Get))
            {
               <p>
                  <h4 style="display:inline-block;"><b>Aranacak Müşteri Adı:</b></h4>  @Html.TextBox("p")

                   <input type="submit" value="Ara" class="btn btn-primary"/>
               </p>
            }

<table class="table table-bordered">
    <tr>
        <th>MÜŞTERİ ID</th>
        <th>MÜŞTERİ AD</th>
        <th>MÜŞTERİ SOYAD</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT</th>
    </tr>
    <tbody>
        @foreach (var musteri in Model)
        {
                <tr>
                    <td>@musteri.MUSTERIID</td>
                    <td>@musteri.MUSTERIAD</td>
                    <td>@musteri.MUSTERISOYAD</td>
                    <td><a href="/MUSTERI/SIL/@musteri.MUSTERIID" class="btn btn-danger">SİL</a></td>
                    <td><a href="/MUSTERI/MusteriGetir/@musteri.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                    <td>@Html.ActionLink("SİL BUTONU", "SIL", new { id = musteri.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor Musunuz?')" })</td>
                </tr>
            }
    </tbody>
</table>
<a class="btn btn-primary" href="/MUSTERI/YeniMusteri">YENİ MÜŞTERİ EKLE</a>

MVCSTOK/Views/Musteri/MusteriGetir.cshtml
@model MVCSTOK.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{

    <div class="form-group">

        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERIAD)
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERISOYAD)
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" } )
        <br />
        <button class="btn btn-warning">Müşteri Güncelle</button>



    </div>

}

MVCSTOK/Views/Musteri/YeniMusteri.cshtml
@model MVCSTOK.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Müşteri Adı</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        <!--<input type="text" class="form-control" name="MUSTERIAD" />-->
        @Html.TextBoxFor(m=>m.MUSTERIAD, new  { @class="form-control"})
        @Html.ValidationMessageFor(m=>m.MUSTERIAD,"",new {style="color:green"})

    </div>
    <div>
        <label>Müşteri Soyadı</label>
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        @*<input type="text" class="form-control" name="MUSTERISOYAD" />*@
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERISOYAD, "", new { style = "color:green" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1">Müşteri Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı...!');

        })
    </script>
</form>