MVCSTOK/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCSTOK.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MVCSTOK.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        MvcDbStokEntities db = new MvcDbStokEntities();

        public ActionResult Index(int sayfa=1)
        {
            //var degerler = db.TBLKATEGORILER.ToList();
            //topagedlist(1,4) demek -hangi sayfadan başlasın 1.sayfadan- 1 sayfada kaçtane öğe olsun 4 tane-
            var degerler = db.TBLKATEGORILER.ToList().ToPagedList(sayfa, 4);
            return View(degerler);
        }

        //httpget demek sayfada işlem yapmıyorsak çalışacak yer.
        [HttpGet]
        public ActionResult yenikategori()
        {
            return View();
        }

        //httpost demek sayfada işlem yaptıktan sonra yaptığımız işlemi sayfaya etkileyerek çalışacak yer.
        [HttpPost]
        public ActionResult yenikategori( TBLKATEGORILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            //add diyerek veritabanına kategori ekleriz.
            db.TBLKATEGORILER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("index");
        }
        public ActionResult SIL(int id)
        {
            var kategori = db.TBLKATEGORILER.Find(id);
            db.TBLKATEGORILER.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");   
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TBLKATEGORILER.Find(id);
            return View("KategoriGetir",ktgr);  
        }
        public ActionResult Guncelle(TBLKATEGORILER p1)
        {
            var ktg = db.TBLKATEGORILER.Find(p1.KATEGORIID);
            ktg.KATEGORIAD=p1.KATEGORIAD;
            db.SaveChanges();
            return RedirectToAction("index");
        }

    }
}

MVCSTOK/Views/Kategori/Index.cshtml
@using MVCSTOK.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLKATEGORILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>KATEGORİ ID</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    <tbody>
        @foreach(var ktgr in Model)
            {
                <tr>
                    <td>@ktgr.KATEGORIID</td>
                    <td>@ktgr.KATEGORIAD</td>
                    <td><a href="/KATEGORI/SIL/@ktgr.KATEGORIID" class="btn btn-danger">SİL</a></td>
                    <td><a href="/KATEGORI/KategoriGetir/@ktgr.KATEGORIID" class="btn btn-success">GÜNCELLE</a></td>
                </tr>
            }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model,sayfa=> Url.Action("Index", new {sayfa}))

<a class="btn btn-primary" href="/KATEGORI/yenikategori/">YENİ KATEGORİ EKLE</a>

MVCSTOK/Views/Kategori/KategoriGetir.cshtml
@model MVCSTOK.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@* html.beginform methodu 3 tane parametre alır.
    1.paramete: bu beginformda bir tetikleme, etkileşim olduğu zaman nereyi çalıştırması gerektiğinin yeri
    2.parametre: çalıştıracağı yerin konumu,  çalıştıracağı yerin nerde sorusuna cevabı.
    3.nezaman çalışacak bu formun cevabı , yani biz birşey gönderdiğimiz zaman form post olduğunda.

*@

@using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.KATEGORIID)
        @Html.TextBoxFor(m => m.KATEGORIID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.KATEGORIAD)
        @Html.TextBoxFor(m => m.KATEGORIAD, new { @class = "form-control" })
    </div>

    <div>
        <button class="btn btn-warning">Kategori Güncelle</button>
    </div>

}

MVCSTOK/Views/Kategori/yenikategori.cshtml
@model MVCSTOK.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "yenikategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@* method="post demek kaydet veya gönder tarzında bir butona bastığımızda arka tarafta httppost olarak tanımladığımız yerin çalışmasını sağlar.. " *@
<form class="form-group" method="post">
    <!--<div>
        <label>Kategori Adı</label>-->
        @* buradaki name veritabınındaki adı ile aynı olmak zorunda.. *@
        <!--<input type="text" class="form-control" name="KATEGORIAD"/>
    </div>-->
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m=>m.KATEGORIAD, new {@class="form-control"})
        @Html.ValidationMessageFor(m=>m.KATEGORIAD,"",new {@style="color:blue"})
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Kategori Ekle</button>
    </div>

</form>